name: leetcode
channels:
  - defaults
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

dependencies:
  - python=3.12
  - jupyter
  - notebook
  - xeus-cling